__title__ = 'DeepCell'
__description__ = 'Deep learning for single cell image segmentation'
__url__ = 'https://github.com/vanvalenlab/deepcell-tf'
__version__ = '0.12.10'
__download_url__ = f'{__url__}/tarball/{__version__}'
__author__ = 'The Van Valen Lab'
__author_email__ = 'vanvalen@caltech.edu'
__license__ = 'LICENSE'
__copyright__ = 'Copyright 2016-2024 The Van Valen Lab at the ' \
    'California Institute of Technology (Caltech)'
